### ISSUE TITLE
crash when attempting to run BDM 1.0.2 Minecraft 1.18 with Fabric API 0.44.0

### ISSUE THREAD

**Issue by Celesian** [Crec0/BetterDarkMode#1]
Hi there, I am running into a crash with BDM

Attempted to run Minecraft 1.18, with fabric loader 0.12.8 with only Fabric API 0.44.0+1.18 and BetterDarkMode 1.0.2 enabled 

https://paste.ee/p/ef6wc paste of my crash log

Steps to reproduce,

1. Install Minecraft 1.18 with Fabric loader 0.12.8
2. Install Fabric Api 0.44 and BetterDarkMode 1.0.2 
3. Load up this modded instance

**Comment by Crec0** [comment]
Yea mod is not ready for 1.18 yet. I will update soon
