### ISSUE TITLE
Unable to load a Minecraft world with BetterDark Mode 1.0.2

### ISSUE THREAD

**Issue by Celesian** [Crec0/BetterDarkMode#2]
https://paste.ee/p/0w2r1 - log

Unable to open a existing/new world with BetterDark Mode 1.0.2. On Minecraft 1.18 with fabric loader 0.12.8

Steps to reproduce 

1. Load Minecraft 1.18 and install  fabric loader 0.12.8
2. Download BetterDark Mode 1.0.2
3. Attempt to create or load an existing world

What happened: I got disconnected or I got this error message https://i.imgur.com/m36OEc5.png

**Comment by Crec0** [comment]
Yea mod is not ready for 1.18 yet. I will update soon
