### ISSUE TITLE
1.16.5 wants to use java16

### ISSUE THREAD

**Issue by superon** [Crec0/BetterDarkMode#3]
tried and failed to trial this on fabric 1.16.5.  first time crashed saying i needed to update the loader version then when i got that done it said:

Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported
so you see i see that's the issue as demonstrated by the title of this issue.

https://minecraft.fandom.com/wiki/Java_Edition_1.16.5 stating
"1.16.5 was the last full version that requires Java 8."
i know that doesn't mean it can't use java16... well, let's be real here.. it sort of totally does ...  i'm still saying this was unintended so reporting it as an issue here

**Comment by Crec0** [comment]
Try out the new release
