### ISSUE TITLE
Does not work with Alloy Forgery REI Recipe Page

### ISSUE THREAD

**Issue by ardissaps** [Crec0/BetterDarkMode#5]
To Reproduce :
1. Install REI, Alloy Forgery, BetterDarkmode
2. Change font to White with this mod
3. Open Alloy Forgery recipe page
4. The font still in Dark Gray

**Comment by Crec0** [comment]
Hey,
I added REI compatibility. You can checkout the 2.1.0 release

**Comment by ardissaps** [comment]
> Hey, I added REI compatibility. You can checkout the 2.1.0 release

Would you please port that to 1.18.2?

**Comment by ardissaps** [comment]
@Crec0

**Comment by Crec0** [comment]
Grab the artifact from there: https://github.com/Crec0/BetterDarkMode/actions/runs/2962066687

**Comment by ardissaps** [comment]
> Grab the artifact from there: https://github.com/Crec0/BetterDarkMode/actions/runs/2962066687

thanks, will it made available public?

**Comment by Crec0** [comment]
I will make a release for it
